services:
    mjrone.codegenerator.createbundle:
        class: MjrOne\CodeGeneratorBundle\Services\CreateBundleService

    mjrone.codegenerator.code.bundle:
        class: MjrOne\CodeGeneratorBundle\Services\GeneratorService\BundleGeneratorService
        arguments:
            - '@mjrone.codegenerator.code.file'

    mjrone.codegenerator.code.file:
        class: MjrOne\CodeGeneratorBundle\Services\GeneratorService\CodeGeneratorService
        arguments:
            - '@mjrone.codegenerator.annotation'
            - '@mjrone.codegenerator.configuration'
            - '@mjrone.codegenerator.renderer'
            - '@kernel'
            - '@mjrone.codegenerator.event'

    mjrone.codegenerator.router:
        class: MjrOne\CodeGeneratorBundle\Services\RouterService
        arguments:
            - '@kernel'
            - '@mjrone.codegenerator.annotation'
            - '@mjrone.codegenerator.configuration'
            - '@mjrone.codegenerator.event'

    mjrone.codegenerator.configuration:
        class: MjrOne\CodeGeneratorBundle\Services\ConfigurationService
        arguments:
            - '%mjrone.codegenerator.configuration%'
            - '@mjrone.codegenerator.event'

    mjrone.codegenerator.annotation:
        class: MjrOne\CodeGeneratorBundle\Services\ReadAnnotationService
        arguments:
            - '@mjrone.codegenerator.event'

    mjrone.codegenerator.renderer:
        class: MjrOne\CodeGeneratorBundle\Services\RenderService
        arguments:
            - '@twig'
            - '@mjrone.codegenerator.event'

    mjrone.codegenerator.event:
        class: MjrOne\CodeGeneratorBundle\Services\EventDispatcherService
        arguments:
            - '@event_dispatcher'
